[package]
name = "caniuse-rs"
version = "0.1.0"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.20"
yew = "0.11.0"
yew-router = "0.8.1"

[build-dependencies]
proc-macro2 = "1.0.8"
serde = { version = "1.0.104", features = ["derive"] }
tera = { version = "1.0.2", default-features = false }
toml = "0.5.6"
quote = "1.0.2"
