[package]
name = "caniuse-rs"
version = "0.1.0"
authors = ["Jonas Platte <jplatte@posteo.de>"]
edition = "2018"

[dependencies]
once_cell = "1.3.1"
stdweb = "0.4.20"
yew = { version = "0.13.2", features = ["std_web"] }
yew-router = { version = "0.10.0", features = ["std_web"] }

[build-dependencies]
proc-macro2 = "1.0.9"
serde = { version = "1.0.104", features = ["derive"] }
tera = { version = "1.0.2", default-features = false }
toml = "0.5.6"
quote = "1.0.3"

[profile.release]
opt-level = "s"
lto = true
