[[features]]
desc_short = "constructor functions in `const fn`"
kind = "lang"
flag = "const_constructor"
version = "1.40.0"

[[features]]
desc_short = "`#![non_exhaustive]`"
kind = "lang"
flag = "non_exhaustive"
version = "1.40.0"
