[unstable]

#[[unstable.features]]

[[versions]]
number = "1.42.0"
channel = "nightly"
gh_milestone_id = 69

[[versions]]
number = "1.41.0"
channel = "beta"
gh_milestone_id = 68

[[versions]]
number = "1.40.0"
blog_post = "https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html"
gh_milestone_id = 67

[[versions.features]]
desc_short = "constructor functions in `const fn`"
kind = "lang"
flag = "const_constructor"

[[versions.features]]
desc_short = "`#![non_exhaustive]`"
kind = "lang"
flag = "non_exhaustive"

[[versions.features]]
desc_short = "macro invocations in `extern {}` blocks"
kind = "lang"
flag = "macros_in_extern"
stabilization_pr_id = 63931

[[versions.features]]
desc_short = "function-like procedural macros in type position"
kind = "lang"
stabilization_pr_id = 63931

[[versions.features]]
desc_short = "proc-macros that generate `macro_rules!` macros"
kind = "lang"
stabilization_pr_id = 64035

[[versions.features]]
desc_short = "`meta` pattern matcher in `macro_rules!` for modern attribute syntax"
kind = "lang"
impl_pr_id = 63674

[[versions.features]]
desc_short = "`#[cfg(doctest)]`"
kind = "lang"
flag = "cfg_doctest"

[[versions.features]]
desc_short = "{float} ↔ bytes conversion"
flag = "float_to_from_bytes"
kind = "stdlib"
items = [
    "f32::to_ne_bytes", "f32::to_le_bytes", "f32::to_be_bytes",
    "f32::from_ne_bytes", "f32::from_le_bytes", "f32::from_be_bytes",

    "f64::to_ne_bytes", "f64::to_le_bytes", "f64::to_be_bytes",
    "f64::from_ne_bytes", "f64::from_le_bytes", "f64::from_be_bytes",
]

[[versions.features]]
desc_short = "`is_power_of_two` as `const fn`"
kind = "stdlib"
impl_pr_id = 65092
items = [
    "u8::is_power_of_two",
    "u16::is_power_of_two",
    "u32::is_power_of_two",
    "u64::is_power_of_two",
    "u128::is_power_of_two",
    "usize::is_power_of_two",
]

[[versions.features]]
desc_short = "`BTreeMap::get_key_value`"
kind = "stdlib"

[[versions.features]]
desc_short = "`HashMap::get_key_value`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Option::as_deref_mut`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Option::as_deref`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Option::flatten`"
kind = "stdlib"

[[versions.features]]
desc_short = "`UdpSocket::peer_addr`"
kind = "stdlib"

[[versions.features]]
desc_short = "`mem::take`"
kind = "stdlib"

[[versions.features]]
desc_short = "`slice::repeat`"
kind = "stdlib"

[[versions.features]]
desc_short = "`todo!`"
kind = "stdlib"

[[versions]]
number = "1.39.0"
blog_post = "https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html"
gh_milestone_id = 66

[[versions.features]]
desc_short = "async / .await"
desc_long = "async fn, `async move {}` blocks and calling `.await` on async expressions"
flag = "async_await"
kind = "lang"

[[versions.features]]
desc_short = "conditional compilation of function arguments"
desc_long = "`#[cfg(...)]` and `#[cfg_attr(...)]` outer attributes on function arguments"
kind = "lang"
stabilization_pr_id = 64010

[[versions.features]]
desc_short = "shared references to bind-by-move patterns in `match` arms' guards"
kind = "lang"
stabilization_pr_id = 63118

[[versions.features]]
desc_short = "`Vec::new` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`String::new` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`LinkedList::new` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`str::len` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`[T]::len` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`str::as_bytes` as `const fn`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Pin::into_inner`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Instant::checked_duration_since`"
kind = "stdlib"

[[versions.features]]
desc_short = "`Instant::saturating_duration_since`"
kind = "stdlib"

[[versions]]
number = "1.38.0"
blog_post = "https://blog.rust-lang.org/2019/09/26/Rust-1.38.0.html"
gh_milestone_id = 65

[[versions.features]]
desc_short = "euclidean division & modulo"
flag = "euclidean_division"
kind = "stdlib"

[[versions]]
number = "1.37.0"
blog_post = "https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html"
gh_milestone_id = 64

[[versions.features]]
desc_short = "`const _: TYPE = VALUE`"
flag = "underscore_const_names"
kind = "lang"

[[versions]]
number = "1.36.0"
blog_post = "https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html"
gh_milestone_id = 62

[[versions]]
number = "1.35.0"
blog_post = "https://blog.rust-lang.org/2019/05/23/Rust-1.35.0.html"
gh_milestone_id = 61

[[versions]]
number = "1.34.0"

[[versions.features]]
desc_short = "`overflowing_neg` as `const fn`"
kind = "stdlib"
items = [
    "i8::overflowing_neg",
    "i16::overflowing_neg",
    "i32::overflowing_neg",
    "i64::overflowing_neg",
    "i128::overflowing_neg",
    "isize::overflowing_neg",
    "u8::overflowing_neg",
    "u16::overflowing_neg",
    "u32::overflowing_neg",
    "u64::overflowing_neg",
    "u128::overflowing_neg",
    "usize::overflowing_neg",
]

[[versions.features]]
desc_short = "`wrapping_neg` as `const fn`"
kind = "stdlib"
items = [
    "i8::wrapping_neg",
    "i16::wrapping_neg",
    "i32::wrapping_neg",
    "i64::wrapping_neg",
    "i128::wrapping_neg",
    "isize::wrapping_neg",
    "u8::wrapping_neg",
    "u16::wrapping_neg",
    "u32::wrapping_neg",
    "u64::wrapping_neg",
    "u128::wrapping_neg",
    "usize::wrapping_neg",
]

[[versions]]
number = "1.32.0"

[[versions.features]]
desc_short = "{integer} ↔ bytes conversion"
flag = "int_to_from_bytes"
kind = "stdlib"
items = [
    "i8::to_ne_bytes", "i8::to_le_bytes", "i8::to_be_bytes",
    "i8::from_ne_bytes", "i8::from_le_bytes", "i8::from_be_bytes",

    "i16::to_ne_bytes", "i16::to_le_bytes", "i16::to_be_bytes",
    "i16::from_ne_bytes", "i16::from_le_bytes", "i16::from_be_bytes",

    "i32::to_ne_bytes", "i32::to_le_bytes", "i32::to_be_bytes",
    "i32::from_ne_bytes", "i32::from_le_bytes", "i32::from_be_bytes",

    "i64::to_ne_bytes", "i64::to_le_bytes", "i64::to_be_bytes",
    "i64::from_ne_bytes", "i64::from_le_bytes", "i64::from_be_bytes",

    "i128::to_ne_bytes", "i128::to_le_bytes", "i128::to_be_bytes",
    "i128::from_ne_bytes", "i128::from_le_bytes", "i128::from_be_bytes",

    "isize::to_ne_bytes", "isize::to_le_bytes", "isize::to_be_bytes",
    "isize::from_ne_bytes", "isize::from_le_bytes", "isize::from_be_bytes",

    "u8::to_ne_bytes", "u8::to_le_bytes", "u8::to_be_bytes",
    "u8::from_ne_bytes", "u8::from_le_bytes", "u8::from_be_bytes",

    "u16::to_ne_bytes", "u16::to_le_bytes", "u16::to_be_bytes",
    "u16::from_ne_bytes", "u16::from_le_bytes", "u16::from_be_bytes",

    "u32::to_ne_bytes", "u32::to_le_bytes", "u32::to_be_bytes",
    "u32::from_ne_bytes", "u32::from_le_bytes", "u32::from_be_bytes",

    "u64::to_ne_bytes", "u64::to_le_bytes", "u64::to_be_bytes",
    "u64::from_ne_bytes", "u64::from_le_bytes", "u64::from_be_bytes",

    "u128::to_ne_bytes", "u128::to_le_bytes", "u128::to_be_bytes",
    "u128::from_ne_bytes", "u128::from_le_bytes", "u128::from_be_bytes",

    "usize::to_ne_bytes", "usize::to_le_bytes", "usize::to_be_bytes",
    "usize::from_ne_bytes", "usize::from_le_bytes", "usize::from_be_bytes",
]

[[versions]]
number = "1.26.0"

[[versions.features]]
desc_short = "placeholder lifetimes (`'_`)"
flag = "underscore_lifetimes"
kind = "lang"

[[versions.features]]
desc_short = "128 bit integer types"
flag = "i128_type"
kind = "lang"
items = ["i128", "u128"]

[[versions]]
number = "1.20.0"

[[versions.features]]
desc_short = "the `compile_error!` macro"
flag = "compile_error"
kind = "stdlib"

[[versions]]
number = "1.6.0"

[[versions.features]]
desc_short = "`#![no_std]`"
flag = "no_std"
kind = "lang"

[[versions]]
number = "1.0.0"

[[versions.features]]
desc_short = "`if let` expressions"
flag = "if_let"
kind = "lang"

[[versions.features]]
desc_short = "`while let` expressions"
flag = "while_let"
kind = "lang"
