[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.11", features = ["derive"] }
hyper = { version = "0.14.18", features = ["http1", "http2", "server", "tcp"] }
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread", "signal"] }
tower = { version = "0.4.12", default-features = false, features = ["make"] }
tower-http = { version = "0.3.3", features = ["fs"] }
xshell = "0.1.17"
